package com.b2i.tontine.domain.account.entity

object UserType {

    const val ACTUATOR = "ACTUATOR"

    const val BACKOFFICE_SUPER_ADMIN = "BACKOFFICE_SUPER_ADMIN"

    const val BACKOFFICE_ADMIN = "BACKOFFICE_ADMIN"

    const val BACKOFFICE_BASIC_USER = "BACKOFFICE_BASIC_USER"

    const val ASSOCIATION_PDG = "ASSOCIATION_PDG"

    const val ASSOCIATION_SECRETARY = "ASSOCIATION_SECRETARY"

    const val ASSOCIATION_TREASURER = "ASSOCIATION_TREASURER"

    const val ASSOCIATION_MEMBER = "ASSOCIATION_MEMBER"
}